name: "setup-java"
description: "Set up Java"
inputs:
  java-version:
    description: "java-version"
    default: 11
    required: false

  distribution:
    description: "distribution"
    default: temurin
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
